spring.application.name=FightKeeperAPI
spring.jpa.show-sql=true
server.port=8080

# AWS Configuration
aws.dynamodb.table=fight-results
aws.region=us-east-2

# Logging
logging.level.root=INFO
logging.level.com.example.fightkeeperapi=DEBUG