spring.application.name=FightKeeperAPI
spring.jpa.show-sql=true
server.port=8080

# AWS Configuration
aws.dynamodb.table=fight-results
aws.region=us-east-1
aws.dynamodb.accessKey=AKIASC3EXPFW7GDUYAN2
aws.dynamodb.secretKey=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
aws.dynamodb.sessionToken=
aws.dynamodb.endpoint=ttps://sns.us-east-1.amazonaws.com

# Logging
logging.level.root=INFO
logging.level.com.example.fightkeeperapi=DEBUG